
# Set to true to show colors, may not work on windows
show_colors: true

# Set Timezone in case not set in php.ini
date_timezone: America/Los_Angeles

phing:
# Does this project have a phing build script?
  enabled: false
# What is the path to the build script relative to the project base dir
# if blank use build.xml
  file: build.xml
# What build targets should be run
# leave blank to run default
# separate multiple targets with spaces
  target: 

# Project Repository
repository:
# Can be svn, hg, or git
  type: svn
# the url of the repository
  url: 
  params:
# credentials
    username: 
    password: 
# you may request a specific revision
    revision:

# set global subversion settings
subversion:
  svn_path: /usr/bin/svn